### PR TITLE
updating gradle

### PR DESCRIPTION
**Pull request by SkyBlade1978**

### CODE REVIEW

**Comment by jriwanek** [comment]
Why 4.1 instead of 4.4?

**Comment by SkyBlade1978** [comment]
I just copied it from one which was working, I think orespawn, can change to 4.4

**Comment by jriwanek** [comment]
Sounds good to me, btw, use `gradlew wrapper --gradle-version 4.4` don't just copy over files (Run it twice to make sure the generation is fully in sync)

**Comment by SkyBlade1978** [comment]
Ah ok cool, new trick for me to learn, I'll do that then

**Review by jriwanek — APPROVED** [review]

**Pull request merged**
